[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#584400'

[colors.cursor]
text = '#131313'
cursor = '#ecc248'

[colors.normal]
black   = '#131313'
red     = '#e14878'
green   = '#94d66e'
yellow  = '#dbb07b'
blue    = '#ae8a22'
magenta = '#b1974e'
cyan    = '#ecc248'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f8b'
green   = '#a6e086'
yellow  = '#e8c497'
blue    = '#f1d188'
magenta = '#9e7138'
cyan    = '#857a36'
white   = '#ffffff'
